# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.6.15

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run counterparty-lib setup and install
          command: python setup.py develop 

      - run: 
          name: Run apsw setup and install
          command: python setup.py install_apsw

      - persist_to_workspace:
          root: ~/
          paths:
            - .      

  test:
    docker:
      - image: cimg/python:3.6.15

    steps:
      - attach_workspace:
          at: ~/
      
      - run:
          name: "Run tests"
          command: "mkdir test-results; py.test --junitxml=test-results/junit.xml --verbose --skiptestbook=all --cov-config=.coveragerc --cov-report=term-missing --cov=./ counterpartylib"

      - store_test_results:
          path: test-results

  test-reparse-testnet:
    docker:
        - image: cimg/python:3.6.15
    
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: "Get latest testnet db file"
          command: |
            mkdir -p ~/.local/share/counterparty
            wget https://counterparty.io/bootstrap/counterparty-db-testnet-7.latest.tar.gz -O ~/.local/share/counterparty/counterparty-db-testnet.latest.tar.gz
            tar -C ~/.local/share/counterparty -xvzf ~/.local/share/counterparty/counterparty-db-testnet.latest.tar.gz
            mv ~/.local/share/counterparty/counterparty.testnet.db ~/.local/share/counterparty/counterparty.db 

      - run:
          name: "Run testnet reparse test"
          command: "mkdir test-results; py.test --junitxml=test-results/junit.xml --verbose --capture=no --skiptestbook=testnet -k test_book counterpartylib/test/reparse_test.py"
      
      - store_test_results:
          path: test-results


workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-reparse-testnet:
          requires:
            - build

