# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.6.15

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run counterparty-lib setup and install
          command: python setup.py develop 

      - run: 
          name: Run apsw setup and install
          command: python setup.py install_apsw

      - persist_to_workspace:
          root: ~/
          paths:
            - .      

  test:
    docker:
      - image: cimg/python:3.6.15

    steps:
      - attach_workspace:
          at: ~/project
      
      - run:
          name: "Run tests"
          command: "cd counterpartylib; py.test --verbose --skiptestbook=all --cov-config=../.coveragerc --cov-report=term-missing --cov=./"

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build

